to: src/controllers/{{ snake_plural }}.rs
skip_exists: true
message: "Controller `{{ pascal_singular }}` (HTML, loco-ui) was added successfully.{% if auth %} Its routes require a JWT — re-run with `--no-auth` to generate public routes.{% endif %}"
injections:
- into: src/controllers/mod.rs
  append: true
  content: "pub mod {{ snake_plural }};"
- into: src/app.rs
  after: "AppRoutes::"
  content: "            .add_route(controllers::{{ snake_plural }}::routes())"
---
{% set_global owned = false -%}
{% for f in fields %}{% if auth and f.field_name == "user_id" %}{% set_global owned = true %}{% endif %}{% endfor -%}
//! {{ pascal_singular }} pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
{%- if owned %}
//!
//! Every row belongs to a user: each query is scoped to the signed-in user (`owner`), and a
//! new row's `user_id` comes from the session, never from the form. Another user's row
//! answers 404.
{%- elif auth %}
//!
//! Every signed-in user sees and changes every row. To give each row an owner, generate the
//! model with a `user:references` field: the controller then scopes every query to the
//! signed-in user.
{%- endif %}
#![allow(clippy::unused_async)]
use loco_ui::{loco::Valid, prelude::*};
use loco_rs::prelude::*;
use serde::Deserialize;
{%- if prelude_use %}
#[allow(unused_imports)] // Loco lists the timestamp types too
{{ prelude_use }}
{%- endif %}

use crate::{
    models::_entities::{{ snake_plural }}::{ActiveModel, Column, Entity, Model},
    views,
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
{%- if f.input_kind == "checkbox" and not f.nullable %}
    #[serde(default, deserialize_with = "loco_ui::loco::checkbox")]
    {{ f.field_name }}: bool,
{%- elif f.input_kind == "datetime" %}
    #[serde({% if f.nullable %}default, {% endif %}deserialize_with = "loco_ui::loco::local")]
    {{ f.field_name }}: {{ f.rust_type }},
{%- elif f.is_enum %}
    {{ f.field_name }}: {% if f.nullable %}Option<String>{% else %}String{% endif %},
{%- else %}
    {{ f.field_name }}: {{ f.rust_type }},
{%- endif %}
{%- endfor %}
}

fn set(item: &mut ActiveModel, p: Params) {
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
    item.{{ f.field_name }} = Set(p.{{ f.field_name }});
{%- endfor %}
}

/// What each reference field can point at: every row of the parent table as `(id, label)`,
/// labelled by its name, title or email (`loco_ui::loco::label`). The form lists them in a
/// select; past a few hundred rows, swap it for `ui.combobox(..)` with a search route.
#[allow(unused_variables)] // `ctx` when the model has no references
async fn refs(ctx: &AppContext) -> Result<views::{{ snake_plural }}::Refs> {
    Ok(views::{{ snake_plural }}::Refs {
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
{%- set is_ref = f.input_kind == "number" and f.field_name is ending_with("_id") and f.rust_type is containing("i64") %}
{%- if is_ref %}
        {{ f.field_name }}: crate::models::_entities::{{ f.field_name | trim_end_matches(pat="_id") | plural }}::Entity::find()
            .all(&ctx.db)
            .await?
            .iter()
            .map(|m| (m.id.to_string(), loco_ui::loco::label(m)))
            .collect(),
{%- endif %}
{%- endfor %}
    })
}

{% if owned %}
/// The signed-in user, whose rows every handler below reads and writes.
async fn owner(ctx: &AppContext, auth: &auth::JWT) -> Result<crate::models::users::Model> {
    Ok(crate::models::users::Model::find_by_pid(&ctx.db, &auth.claims.pid).await?)
}

/// Row `id` if it belongs to `owner`, else 404.
async fn load(ctx: &AppContext, id: i64, owner: i64) -> Result<Model> {
    Entity::find_by_id(id).filter(Column::UserId.eq(owner)).one(&ctx.db).await?.ok_or(Error::NotFound)
}
{% else %}
async fn load(ctx: &AppContext, id: i64) -> Result<Model> {
    Entity::find_by_id(id).one(&ctx.db).await?.ok_or(Error::NotFound)
}
{% endif %}

#[debug_handler]
async fn list(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
) -> Result<Page> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    let table = ui.table("{{ snake_plural }}", "");
    let wanted = query::PaginationQuery {
        page: table.page() as u64,
        page_size: table.per_page() as u64,
    };
    let found = query::fetch_page(&ctx.db, Entity::find(){% if owned %}.filter(Column::UserId.eq(me.id)){% endif %}.order_by_asc(Column::Id), &wanted).await?;
    Ok(ui.page("{{ pascal_plural }}", views::{{ snake_plural }}::list(&ui, &found.page, &found.meta)))
}

#[debug_handler]
async fn show(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    let item = load(&ctx, id{% if owned %}, me.id{% endif %}).await?;
    Ok(ui.page("{{ pascal_singular }}", views::{{ snake_plural }}::show(&ui, &item)))
}

#[debug_handler]
async fn new(
{% if auth %}    _auth: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
) -> Result<Page> {
    let title = "New {{ snake_singular | replace(from="_", to=" ") }}";
    let form = views::{{ snake_plural }}::form(&ui, title, "/{{ snake_plural }}", &[], &[], &refs(&ctx).await?);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn create(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "New {{ snake_singular | replace(from="_", to=" ") }}";
            let body = views::{{ snake_plural }}::form(&ui, title, "/{{ snake_plural }}", &bad.values, &bad.errors.pairs(), &refs(&ctx).await?);
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, p);
{%- if owned %}
    item.user_id = Set(me.id);
{%- endif %}
    let item = item.insert(&ctx.db).await?;
    let to = format!("/{{ snake_plural }}/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    let item = load(&ctx, id{% if owned %}, me.id{% endif %}).await?;
    let action = format!("/{{ snake_plural }}/{id}");
    let title = "Edit {{ snake_singular | replace(from="_", to=" ") }}";
    let form = views::{{ snake_plural }}::form(&ui, title, &action, &views::{{ snake_plural }}::values(&item), &[], &refs(&ctx).await?);
    Ok(ui.page(title, form))
}

#[debug_handler]
async fn update(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    let item = load(&ctx, id{% if owned %}, me.id{% endif %}).await?;
    let action = format!("/{{ snake_plural }}/{id}");
    let p = match form {
        Ok(p) => p,
        Err(bad) => {
            let title = "Edit {{ snake_singular | replace(from="_", to=" ") }}";
            let body = views::{{ snake_plural }}::form(&ui, title, &action, &bad.values, &bad.errors.pairs(), &refs(&ctx).await?);
            return Ok(ui.page(title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, p);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
{% if auth %}    {% if owned %}auth{% else %}_auth{% endif %}: auth::JWT,
{% endif %}    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
{% if owned %}    let me = owner(&ctx, &auth).await?;
{% endif %}    load(&ctx, id{% if owned %}, me.id{% endif %}).await?.into_active_model().delete(&ctx.db).await?;
    Ok(ui.redirect("/{{ snake_plural }}").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/{{ snake_plural }}")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
