//! Notebook pages: list, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates, then edited: the show page lists the
//! notebook's notes under its card.

use loco_rs::controller::views::pagination::PagerMeta;
use loco_ui::{prelude::*, table::Row};

use crate::{
    models::{_entities::notebooks::Model, notes::Listed},
    views::notes::card,
};

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![("name".into(), m.name.to_string())]
}

/// Every notebook on this page, with the pager from Loco's paging answer.
pub fn list(ui: &Ui, rows: &[Model], meta: &PagerMeta) -> Markup {
    let table = ui
        .table("notebooks", "/notebooks")
        .column("id", "Id")
        .column("name", "Name");
    let rows = rows.iter().map(|m| {
        let v = values(m);
        let href = format!("/notebooks/{}", m.id);
        let mut cells = vec![html! { a href=(href) { (m.id) } }];
        cells.extend(v.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    html! {
        h1 { "Notebooks" }
        (table.rows(rows).paged_from(meta))
        (ui.link_button("New notebook", "/notebooks/new"))
    }
}

/// One notebook: its fields in a card, with back, edit and delete beside the title, and
/// then its notes.
pub fn show(ui: &Ui, m: &Model, notes: &[Listed]) -> Markup {
    let labels = ["Name"];
    let title = m.name.clone();
    let action = format!("/notebooks/{}/delete", m.id);
    let edit = format!("/notebooks/{}/edit", m.id);
    let page = ui
        .record_page(&title)
        .back("/notebooks")
        .edit(&edit)
        .delete(&action);
    let page =
        (labels.iter().zip(values(m))).fold(page, |p, (label, (_, value))| p.field(label, value));
    let new = format!("/notes/new?notebook={}", m.id);
    let count = notes.len().to_string();
    let page = page
        .field("Notes", count.as_str())
        .field("Created", m.created_at.format("%-d %b %Y").to_string());
    html! {
        (page)
        div class="notes-section" {
            div class="notes-bar" {
                h2 { "Notes in " (m.name) }
                (ui.link_button("New note here", &new).primary())
            }
            @if notes.is_empty() {
                (ui.empty_state("No notes yet").icon(Icon::File).link("New note here", &new))
            } @else {
                (ui.grid("17rem").body(html! { @for it in notes { (card(ui, it)) } }))
            }
        }
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    let form = ui
        .form(action)
        .text("name", "Name")
        .required()
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
