//! Notebook pages: list, show, and the form for new and edit, written in `lui!`.
//! Generated by the loco-ui scaffold templates, then edited: the show page lists the
//! notebook's notes under its card.

use loco_rs::controller::views::pagination::PagerMeta;
use loco_ui::{prelude::*, table::Row};

use crate::{
    models::{_entities::notebooks::Model, notes::Listed},
    views::notes::card,
};

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(notebook: &Model) -> Vec<(String, String)> {
    vec![("name".into(), notebook.name.to_string())]
}

/// Every notebook on this page, with the pager from Loco's paging answer.
pub fn list(ui: &Ui, rows: &[Model], meta: &PagerMeta) -> Markup {
    let rows = rows.iter().map(|notebook| {
        let fields = values(notebook);
        let href = format!("/notebooks/{}", notebook.id);
        let mut cells = vec![html! { a href=(href) { (notebook.id) } }];
        cells.extend(fields.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    lui! {
        h1 { "Notebooks" }
        Table("notebooks", "/notebooks") rows=(rows) paged_from=(meta) {
            column "id" "Id";
            column "name" "Name";
        }
        LinkButton("New notebook", "/notebooks/new");
    }
}

/// One notebook: its fields in a card, with back, edit and delete beside the title, and
/// then its notes.
pub fn show(ui: &Ui, notebook: &Model, notes: &[Listed]) -> Markup {
    let labels = ["Name"];
    let title = notebook.name.clone();
    let action = format!("/notebooks/{}/delete", notebook.id);
    let edit = format!("/notebooks/{}/edit", notebook.id);
    let new = format!("/notes/new?notebook={}", notebook.id);
    let count = notes.len().to_string();
    lui! {
        RecordPage(&title) back="/notebooks" edit=(&edit) delete=(&action) {
            @for (label, (_, value)) in labels.iter().zip(values(notebook)) {
                field (label) (value);
            }
            field "Notes" (count.as_str());
            field "Created" (notebook.created_at.format("%-d %b %Y").to_string());
        }
        div class="notes-section" {
            div class="notes-bar" {
                h2 { "Notes in " (notebook.name) }
                LinkButton("New note here", &new) primary;
            }
            @if notes.is_empty() {
                EmptyState("No notes yet") icon=(Icon::File) { link "New note here" (&new); }
            } @else {
                Grid("17rem") { @for note in notes { (card(ui, note)) } }
            }
        }
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    lui! {
        h1 { (title) }
        Form(action) values=(values) errors=(errors) submit="Save" {
            text "name" "Name" required;
        }
    }
}
