//! Task pages: a board and a table, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates, then edited: the list is tabs of a board and
//! a table, and pages sit in the app shell.

use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::tasks::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![
        ("title".into(), m.title.to_string()),
        ("done".into(), m.done.to_string()),
        (
            "due_on".into(),
            m.due_on
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        (
            "starts_at".into(),
            m.starts_at
                .map(|v| v.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "remind_at".into(),
            m.remind_at
                .map(|v| v.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "price".into(),
            m.price
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("status".into(), m.status.to_string()),
        (
            "size".into(),
            m.size.as_ref().map(ToString::to_string).unwrap_or_default(),
        ),
    ]
}

/// The tasks as a board (move a card to change its status) and as a table, in two tabs.
pub fn list(ui: &Ui, rows: &[Model]) -> Markup {
    let ids: Vec<String> = rows.iter().map(|m| m.id.to_string()).collect();
    let dates: Vec<String> = (rows.iter())
        .map(|m| {
            m.due_on
                .map(|d| format!("Due {}", d.format("%-d %b")))
                .unwrap_or_default()
        })
        .collect();
    let mut board = ui.kanban("/tasks/move");
    for (key, title) in [("todo", "To do"), ("doing", "Doing"), ("done", "Done")] {
        board = board.column(key, title);
        for ((m, id), date) in rows
            .iter()
            .zip(&ids)
            .zip(&dates)
            .filter(|((m, _), _)| m.status == key)
        {
            board = board.card(id, &m.title);
            if !date.is_empty() {
                board = board.description(date);
            }
            if let Some(size) = m.size {
                board = board.badge(size);
            }
        }
    }
    let table = ui
        .table("tasks", "/tasks")
        .column("title", "Title")
        .column("status", "Status")
        .column("due_on", "Due on")
        .column("price", "Price")
        .column("size", "Size")
        .hide_search();
    let cells = rows.iter().map(|m| {
        Row::new([
            html! { a href={ "/tasks/" (m.id) } { (m.title) } },
            html! { (ui.badge(&m.status).secondary()) },
            html! { (m.due_on.map(|d| d.to_string()).unwrap_or_default()) },
            html! { (m.price.map(|p| p.to_string()).unwrap_or_default()) },
            html! { (m.size.map(|s| s.to_string()).unwrap_or_default()) },
        ])
    });
    let open = rows.iter().filter(|m| m.status != "done").count();
    html! {
        div class="notes-bar" {
            h1 { "Tasks" }
            (ui.link_button("New task", "/tasks/new").primary())
        }
        (ui.tabs("tasks").tab("Board", board.render()).badge(open).tab("Table", table.rows(cells).render()))
    }
}

/// One task: its fields in a card, with back, edit and delete beside the title.
pub fn show(ui: &Ui, m: &Model) -> Markup {
    let labels = [
        "Title",
        "Done",
        "Due on",
        "Starts at",
        "Remind at",
        "Price",
        "Status",
        "Size",
    ];
    let title = format!("Task {}", m.id);
    let action = format!("/tasks/{}/delete", m.id);
    let edit = format!("/tasks/{}/edit", m.id);
    let page = ui
        .record_page(&title)
        .back("/tasks")
        .edit(&edit)
        .delete(&action);
    let page =
        (labels.iter().zip(values(m))).fold(page, |p, (label, (_, value))| p.field(label, value));
    html! {
        (page)
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    let form = ui
        .form(action)
        .text("title", "Title")
        .required()
        .checkbox("done", "Done")
        .date("due_on", "Due on", "1900-01-01", "2100-12-31")
        .datetime("starts_at", "Starts at", "", "")
        .datetime("remind_at", "Remind at", "", "")
        .pattern(
            "price",
            "Price",
            "-?[0-9]+([.][0-9]+)?",
            "A number, like 12.50.",
        )
        .select("status", "Status", ["todo", "doing", "done"])
        .required()
        .number("size", "Size", i32::MIN.into(), i32::MAX.into())
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
