//! Task pages: list, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates; edit freely.

use loco_rs::controller::views::pagination::PagerMeta;
use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::tasks::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![
        ("title".into(), m.title.to_string()),
        ("done".into(), m.done.to_string()),
        (
            "due_on".into(),
            m.due_on
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        (
            "starts_at".into(),
            m.starts_at
                .map(|v| v.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "remind_at".into(),
            m.remind_at
                .map(|v| v.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "price".into(),
            m.price
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("status".into(), m.status.to_string()),
        (
            "size".into(),
            m.size.as_ref().map(ToString::to_string).unwrap_or_default(),
        ),
    ]
}

/// Every task on this page, with the pager from Loco's paging answer.
pub fn list(ui: &Ui, rows: &[Model], meta: &PagerMeta) -> Markup {
    let table = ui
        .table("tasks", "/tasks")
        .column("id", "Id")
        .column("title", "Title")
        .column("done", "Done")
        .column("due_on", "Due on")
        .column("starts_at", "Starts at")
        .column("remind_at", "Remind at")
        .column("price", "Price")
        .column("status", "Status")
        .column("size", "Size");
    let rows = rows.iter().map(|m| {
        let v = values(m);
        let href = format!("/tasks/{}", m.id);
        let mut cells = vec![html! { a href=(href) { (m.id) } }];
        cells.extend(v.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    html! {
        (ui.flash())
        h1 { "Tasks" }
        (table.rows(rows).paged_from(meta))
        (ui.link_button("New task", "/tasks/new"))
    }
}

/// One task: its fields in a card, with back, edit and delete beside the title.
pub fn show(ui: &Ui, m: &Model) -> Markup {
    let labels = [
        "Title",
        "Done",
        "Due on",
        "Starts at",
        "Remind at",
        "Price",
        "Status",
        "Size",
    ];
    let title = format!("Task {}", m.id);
    let action = format!("/tasks/{}/delete", m.id);
    let edit = format!("/tasks/{}/edit", m.id);
    let page = ui
        .record_page(&title)
        .back("/tasks")
        .edit(&edit)
        .delete(&action);
    let page =
        (labels.iter().zip(values(m))).fold(page, |p, (label, (_, value))| p.field(label, value));
    html! {
        (ui.flash())
        (page)
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    let form = ui
        .form(action)
        .text("title", "Title")
        .required()
        .checkbox("done", "Done")
        .date("due_on", "Due on", "1900-01-01", "2100-12-31")
        .datetime("starts_at", "Starts at", "", "")
        .datetime("remind_at", "Remind at", "", "")
        .pattern(
            "price",
            "Price",
            "-?[0-9]+([.][0-9]+)?",
            "A number, like 12.50.",
        )
        .select("status", "Status", ["todo", "doing", "done"])
        .required()
        .number("size", "Size", i32::MIN.into(), i32::MAX.into())
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
