//! Task pages: a board and a table, show, and the form for new and edit, written in `lui!`.
//! Generated by the loco-ui scaffold templates, then edited: the list is tabs of a board and
//! a table, and pages sit in the app shell.

use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::tasks::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(task: &Model) -> Vec<(String, String)> {
    vec![
        ("title".into(), task.title.to_string()),
        ("done".into(), task.done.to_string()),
        (
            "due_on".into(),
            task.due_on
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        (
            "starts_at".into(),
            task.starts_at
                .map(|time| time.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "remind_at".into(),
            task.remind_at
                .map(|time| time.format("%Y-%m-%dT%H:%M").to_string())
                .unwrap_or_default(),
        ),
        (
            "price".into(),
            task.price
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
        ("status".into(), task.status.to_string()),
        (
            "size".into(),
            task.size
                .as_ref()
                .map(ToString::to_string)
                .unwrap_or_default(),
        ),
    ]
}

/// The tasks as a board (move a card to change its status) and as a table, in two tabs.
pub fn list(ui: &Ui, rows: &[Model]) -> Markup {
    let ids: Vec<String> = rows.iter().map(|task| task.id.to_string()).collect();
    let dates: Vec<String> = (rows.iter())
        .map(|task| {
            task.due_on
                .map(|date| format!("Due {}", date.format("%-d %b")))
                .unwrap_or_default()
        })
        .collect();
    let mut columns = [("todo", "To do"), ("doing", "Doing"), ("done", "Done")]
        .map(|(key, title)| (key, title, Vec::new()));
    for ((task, id), date) in rows.iter().zip(&ids).zip(&dates) {
        if let Some((_, _, cards)) = columns.iter_mut().find(|(key, _, _)| *key == task.status) {
            cards.push((task, id.as_str(), date.as_str()));
        }
    }
    let cells = rows.iter().map(|task| {
        Row::new([
            html! { a href={ "/tasks/" (task.id) } { (task.title) } },
            lui! { Badge(&task.status) secondary; },
            html! { (task.due_on.map(|date| date.to_string()).unwrap_or_default()) },
            html! { (task.price.map(|price| price.to_string()).unwrap_or_default()) },
            html! { (task.size.map(|size| size.to_string()).unwrap_or_default()) },
        ])
    });
    let open = rows.iter().filter(|task| task.status != "done").count();
    lui! {
        div class="notes-bar" {
            h1 { "Tasks" }
            LinkButton("New task", "/tasks/new") primary;
        }
        Tabs("tasks") {
            tab "Board" badge=(open) {
                Kanban("/tasks/move") {
                    @for (key, title, cards) in &columns {
                        column (*key) (*title) {
                            @for &(task, id, date) in cards {
                                card (id) (&task.title) description=[(!date.is_empty()).then_some(date)] badge=[task.size];
                            }
                        }
                    }
                }
            }
            tab "Table" {
                Table("tasks", "/tasks") hide_search rows=(cells) {
                    column "title" "Title";
                    column "status" "Status";
                    column "due_on" "Due on";
                    column "price" "Price";
                    column "size" "Size";
                }
            }
        }
    }
}

/// One task: its fields in a card, with back, edit and delete beside the title.
pub fn show(ui: &Ui, task: &Model) -> Markup {
    let labels = [
        "Title",
        "Done",
        "Due on",
        "Starts at",
        "Remind at",
        "Price",
        "Status",
        "Size",
    ];
    let title = format!("Task {}", task.id);
    let action = format!("/tasks/{}/delete", task.id);
    let edit = format!("/tasks/{}/edit", task.id);
    lui! {
        RecordPage(&title) back="/tasks" edit=(&edit) delete=(&action) {
            @for (label, (_, value)) in labels.iter().zip(values(task)) {
                field (label) (value);
            }
        }
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    lui! {
        h1 { (title) }
        Form(action) values=(values) errors=(errors) submit="Save" {
            text "title" "Title" required;
            checkbox "done" "Done";
            date "due_on" "Due on" "1900-01-01" "2100-12-31";
            datetime "starts_at" "Starts at" "" "";
            datetime "remind_at" "Remind at" "" "";
            pattern "price" "Price" "-?[0-9]+([.][0-9]+)?" "A number, like 12.50.";
            select "status" "Status" (["todo", "doing", "done"]) required;
            number "size" "Size" (i32::MIN.into()) (i32::MAX.into());
        }
    }
}
