to: src/views/{{ snake_plural }}.rs
skip_exists: true
message: "Views `views::{{ snake_plural }}` (Maud, loco-ui) were added successfully."
injections:
- into: src/views/mod.rs
  append: true
  content: "pub mod {{ snake_plural }};"
---
{% set_global owned = false -%}
{% for f in fields %}{% if auth and f.field_name == "user_id" %}{% set_global owned = true %}{% endif %}{% endfor -%}
//! {{ pascal_singular }} pages: list, show, and the form for new and edit, built from `ui.*`.
//! Generated by the loco-ui scaffold templates; edit freely.

use loco_rs::controller::views::pagination::PagerMeta;
use loco_ui::{prelude::*, table::Row};

use crate::models::_entities::{{ snake_plural }}::Model;

/// The model as the form's `(name, value)` pairs, for the edit page.
pub fn values(m: &Model) -> Vec<(String, String)> {
    vec![
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
{%- if f.input_kind == "datetime" %}
{%- if f.rust_type is containing("DateTime") %}{% set shape = "%Y-%m-%dT%H:%M" %}{% else %}{% set shape = "%H:%M" %}{% endif %}
{%- if f.nullable %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.map(|v| v.format("{{ shape }}").to_string()).unwrap_or_default()),
{%- else %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.format("{{ shape }}").to_string()),
{%- endif %}
{%- elif f.nullable %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.as_ref().map(ToString::to_string).unwrap_or_default()),
{%- else %}
        ("{{ f.field_name }}".into(), m.{{ f.field_name }}.to_string()),
{%- endif %}
{%- endfor %}
    ]
}

/// Every {{ snake_singular }} on this page, with the pager from Loco's paging answer.
pub fn list(ui: &Ui, rows: &[Model], meta: &PagerMeta) -> Markup {
    let table = ui
        .table("{{ snake_plural }}", "/{{ snake_plural }}")
        .column("id", "Id")
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
        .column("{{ f.field_name }}", "{{ f.label }}")
{%- endfor %};
    let rows = rows.iter().map(|m| {
        let v = values(m);
        let href = format!("/{{ snake_plural }}/{}", m.id);
        let mut cells = vec![html! { a href=(href) { (m.id) } }];
        cells.extend(v.iter().map(|(_, value)| html! { (value) }));
        Row::new(cells)
    });
    html! {
        (ui.flash())
        h1 { "{{ pascal_plural }}" }
        (table.rows(rows).paged_from(meta))
        (ui.link_button("New {{ snake_singular | replace(from="_", to=" ") }}", "/{{ snake_plural }}/new"))
    }
}

/// One {{ snake_singular }}: its fields in a card, with back, edit and delete beside the title.
pub fn show(ui: &Ui, m: &Model) -> Markup {
    let labels = [{% for f in fields %}{% if owned and f.field_name == "user_id" %}{% continue %}{% endif %}"{{ f.label }}", {% endfor %}];
    let title = format!("{{ pascal_singular | replace(from="_", to=" ") }} {}", m.id);
    let action = format!("/{{ snake_plural }}/{}/delete", m.id);
    let edit = format!("/{{ snake_plural }}/{}/edit", m.id);
    let page = ui
        .record_page(&title)
        .back("/{{ snake_plural }}")
        .edit(&edit)
        .delete(&action);
    let page =
        (labels.iter().zip(values(m))).fold(page, |p, (label, (_, value))| p.field(label, value));
    html! {
        (ui.flash())
        (page)
    }
}

/// The rows each reference field can point at, as `(id, label)`, loaded by the controller.
#[derive(Debug, Default)]
pub struct Refs {
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
{%- set is_ref = f.input_kind == "number" and f.field_name is ending_with("_id") and f.rust_type is containing("i64") %}
{%- if is_ref %}
    pub {{ f.field_name }}: Vec<(String, String)>,
{%- endif %}
{%- endfor %}
}

/// The form for new (`action` = the list) and edit (`action` = the item), with what was
/// posted and the messages when it comes back.
#[allow(unused_variables)] // `refs` when the model has no references
pub fn form(
    ui: &Ui,
    title: &str,
    action: &str,
    values: &[(String, String)],
    errors: &[(&str, &str)],
    refs: &Refs,
) -> Markup {
    let form = ui
        .form(action)
{%- for f in fields %}
{%- if owned and f.field_name == "user_id" %}{% continue %}{% endif %}
{%- set is_ref = f.input_kind == "number" and f.field_name is ending_with("_id") and f.rust_type is containing("i64") %}
{%- if is_ref %}
        .select(
            "{{ f.field_name }}",
            "{{ f.label | trim_end_matches(pat=" id") }}",
            {% if f.nullable %}std::iter::once(("", "None")).chain({% endif %}refs.{{ f.field_name }}.iter().map(|(id, label)| (id.as_str(), label.as_str())){% if f.nullable %}){% endif %},
        )
{%- elif f.is_enum %}
        .select("{{ f.field_name }}", "{{ f.label }}", [{% for e in enums %}{% if e.enum_type == f.enum_type %}{% for v in e.variants %}"{{ v.value }}", {% endfor %}{% endif %}{% endfor %}])
{%- elif f.input_kind == "checkbox" %}
        .checkbox("{{ f.field_name }}", "{{ f.label }}")
{%- elif f.input_kind == "textarea" %}
        .textarea("{{ f.field_name }}", "{{ f.label }}", 4)
{%- elif f.input_kind == "date" %}
        .date("{{ f.field_name }}", "{{ f.label }}", "1900-01-01", "2100-12-31")
{%- elif f.input_kind == "datetime" and f.rust_type is containing("DateTime") %}
        .datetime("{{ f.field_name }}", "{{ f.label }}", "", "")
{%- elif f.input_kind == "datetime" %}
        .time("{{ f.field_name }}", "{{ f.label }}", "", "")
{%- elif f.input_kind == "text_number" or f.rust_type is containing("f32") or f.rust_type is containing("f64") %}
        .pattern("{{ f.field_name }}", "{{ f.label }}", "-?[0-9]+([.][0-9]+)?", "A number, like 12.50.")
{%- elif f.input_kind == "number" and f.rust_type is containing("i16") %}
        .number("{{ f.field_name }}", "{{ f.label }}", i16::MIN.into(), i16::MAX.into())
{%- elif f.input_kind == "number" %}
        .number("{{ f.field_name }}", "{{ f.label }}", i32::MIN.into(), i32::MAX.into())
{%- else %}
        .text("{{ f.field_name }}", "{{ f.label }}")
{%- endif %}
{%- if not f.nullable and f.input_kind != "checkbox" %}
        .required()
{%- endif %}
{%- endfor %}
        .values(values)
        .errors(errors)
        .submit("Save");
    html! {
        h1 { (title) }
        (form)
    }
}
