//! Notebook pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
//!
//! Every row belongs to a user: each query is scoped to the signed-in user (`owner`), and a
//! new row's `user_id` comes from the session, never from the form. Another user's row
//! answers 404.
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use loco_ui::{loco::Valid, prelude::*};
#[allow(unused_imports)] // Loco lists the timestamp types too
use sea_orm::prelude::DateTimeWithTimeZone;
use serde::Deserialize;

use crate::{
    controllers::session::{nav, owner},
    models::_entities::notebooks::{ActiveModel, Column, Entity, Model},
    views::{self, shell},
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
    name: String,
}

fn set(item: &mut ActiveModel, params: Params) {
    item.name = Set(params.name);
}

/// What each reference field can point at: every row of the parent table as `(id, label)`,
/// labelled by its name, title or email (`loco_ui::loco::label`). The form lists them in a
/// select; past a few hundred rows, swap it for `ui.combobox(..)` with a search route.
#[allow(unused_variables)] // `ctx` when the model has no references
async fn refs(ctx: &AppContext) -> Result<views::notebooks::Refs> {
    Ok(views::notebooks::Refs {})
}

/// Row `id` if it belongs to `owner`, else 404.
async fn load(ctx: &AppContext, id: i64, owner: i64) -> Result<Model> {
    Entity::find_by_id(id)
        .filter(Column::UserId.eq(owner))
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let table = ui.table("notebooks", "");
    let wanted = query::PaginationQuery {
        page: table.page() as u64,
        page_size: table.per_page() as u64,
    };
    let found = query::fetch_page(
        &ctx.db,
        Entity::find()
            .filter(Column::UserId.eq(me.id))
            .order_by_asc(Column::Id),
        &wanted,
    )
    .await?;
    Ok(shell::page(
        &ui,
        &nav(&ctx, &me).await?,
        "Notebooks",
        views::notebooks::list(&ui, &found.page, &found.meta),
    ))
}

#[debug_handler]
async fn show(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    let notes = crate::models::notes::Entity::listed(&ctx.db, me.id, |query| {
        query
            .filter(crate::models::notes::Column::NotebookId.eq(id))
            .filter(crate::models::notes::Column::Archived.eq(false))
    })
    .await?;
    let body = views::notebooks::show(&ui, &item, &notes);
    Ok(shell::page(&ui, &nav(&ctx, &me).await?, &item.name, body))
}

#[debug_handler]
async fn new(auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let title = "New notebook";
    let form = views::notebooks::form(&ui, title, "/notebooks", &[], &[], &refs(&ctx).await?);
    Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, form))
}

#[debug_handler]
async fn create(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let me = owner(&ctx, &auth).await?;
    let params = match form {
        Ok(params) => params,
        Err(bad) => {
            let title = "New notebook";
            let body = views::notebooks::form(
                &ui,
                title,
                "/notebooks",
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, params);
    item.user_id = Set(me.id);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/notebooks/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    let action = format!("/notebooks/{id}");
    let title = "Edit notebook";
    let form = views::notebooks::form(
        &ui,
        title,
        &action,
        &views::notebooks::values(&item),
        &[],
        &refs(&ctx).await?,
    );
    Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, form))
}

#[debug_handler]
async fn update(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    let action = format!("/notebooks/{id}");
    let params = match form {
        Ok(params) => params,
        Err(bad) => {
            let title = "Edit notebook";
            let body = views::notebooks::form(
                &ui,
                title,
                &action,
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, params);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    let me = owner(&ctx, &auth).await?;
    load(&ctx, id, me.id)
        .await?
        .into_active_model()
        .delete(&ctx.db)
        .await?;
    Ok(ui.redirect("/notebooks").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/notebooks")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
