//! Task pages: list, show, new, edit and delete as plain HTML forms with
//! Post/Redirect/Get. Generated by the loco-ui scaffold templates; edit freely.
//!
//! Every row belongs to a user: each query is scoped to the signed-in user (`owner`), and a
//! new row's `user_id` comes from the session, never from the form. Another user's row
//! answers 404.
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use loco_ui::{loco::Valid, prelude::*};
#[allow(unused_imports)] // Loco lists the timestamp types too
use sea_orm::prelude::{Date, DateTime, DateTimeWithTimeZone, Decimal};
use serde::Deserialize;

use crate::{
    controllers::session::{nav, owner},
    models::_entities::tasks::{ActiveModel, Column, Entity, Model},
    views::{self, shell},
};

/// The posted fields. `Valid<Params>` reads them, or gives back a message for every field in
/// error and what was posted; add `#[validate(..)]` rules here.
#[derive(Deserialize, Validate)]
struct Params {
    title: String,
    #[serde(default, deserialize_with = "loco_ui::loco::checkbox")]
    done: bool,
    due_on: Option<Date>,
    #[serde(default, deserialize_with = "loco_ui::loco::local")]
    starts_at: Option<DateTime>,
    #[serde(default, deserialize_with = "loco_ui::loco::local")]
    remind_at: Option<DateTimeWithTimeZone>,
    price: Option<Decimal>,
    status: String,
    size: Option<i64>,
}

fn set(item: &mut ActiveModel, params: Params) {
    item.title = Set(params.title);
    item.done = Set(params.done);
    item.due_on = Set(params.due_on);
    item.starts_at = Set(params.starts_at);
    item.remind_at = Set(params.remind_at);
    item.price = Set(params.price);
    item.status = Set(params.status);
    item.size = Set(params.size);
}

/// What each reference field can point at: every row of the parent table as `(id, label)`,
/// labelled by its name, title or email (`loco_ui::loco::label`). The form lists them in a
/// select; past a few hundred rows, swap it for `ui.combobox(..)` with a search route.
#[allow(unused_variables)] // `ctx` when the model has no references
async fn refs(ctx: &AppContext) -> Result<views::tasks::Refs> {
    Ok(views::tasks::Refs {})
}

/// Row `id` if it belongs to `owner`, else 404.
async fn load(ctx: &AppContext, id: i64, owner: i64) -> Result<Model> {
    Entity::find_by_id(id)
        .filter(Column::UserId.eq(owner))
        .one(&ctx.db)
        .await?
        .ok_or(Error::NotFound)
}

#[debug_handler]
async fn list(auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let mut found = Entity::find()
        .filter(Column::UserId.eq(me.id))
        .all(&ctx.db)
        .await?;
    found.sort_by_key(|task| (task.due_on.is_none(), task.due_on));
    Ok(shell::page(
        &ui,
        &nav(&ctx, &me).await?,
        "Tasks",
        views::tasks::list(&ui, &found),
    ))
}

/// What the board posts when a card moves: the task and its new column.
#[derive(Deserialize)]
struct Move {
    card: i64,
    to: String,
}

/// Move a task to another column of the board: its status (and whether it is done).
#[debug_handler]
async fn move_card(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Form(moved): Form<Move>,
) -> Result<Redirect> {
    let me = owner(&ctx, &auth).await?;
    if !["todo", "doing", "done"].contains(&moved.to.as_str()) {
        return Err(Error::BadRequest("no such column".into()));
    }
    let mut item = load(&ctx, moved.card, me.id).await?.into_active_model();
    item.done = Set(moved.to == "done");
    item.status = Set(moved.to);
    item.update(&ctx.db).await?;
    Ok(ui.redirect("/tasks"))
}

#[debug_handler]
async fn show(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    Ok(shell::page(
        &ui,
        &nav(&ctx, &me).await?,
        "Task",
        views::tasks::show(&ui, &item),
    ))
}

#[debug_handler]
async fn new(auth: auth::JWT, ui: Ui, State(ctx): State<AppContext>) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let title = "New task";
    let form = views::tasks::form(&ui, title, "/tasks", &[], &[], &refs(&ctx).await?);
    Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, form))
}

#[debug_handler]
async fn create(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let me = owner(&ctx, &auth).await?;
    let params = match form {
        Ok(params) => params,
        Err(bad) => {
            let title = "New task";
            let body = views::tasks::form(
                &ui,
                title,
                "/tasks",
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, body).into_response());
        }
    };
    let mut item = ActiveModel {
        ..Default::default()
    };
    set(&mut item, params);
    item.user_id = Set(me.id);
    let item = item.insert(&ctx.db).await?;
    let to = format!("/tasks/{}", item.id);
    Ok(ui.redirect(&to).ok("Created.").into_response())
}

#[debug_handler]
async fn edit(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Page> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    let action = format!("/tasks/{id}");
    let title = "Edit task";
    let form = views::tasks::form(
        &ui,
        title,
        &action,
        &views::tasks::values(&item),
        &[],
        &refs(&ctx).await?,
    );
    Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, form))
}

#[debug_handler]
async fn update(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
    Valid(form): Valid<Params>,
) -> Result<Response> {
    let me = owner(&ctx, &auth).await?;
    let item = load(&ctx, id, me.id).await?;
    let action = format!("/tasks/{id}");
    let params = match form {
        Ok(params) => params,
        Err(bad) => {
            let title = "Edit task";
            let body = views::tasks::form(
                &ui,
                title,
                &action,
                &bad.values,
                &bad.errors.pairs(),
                &refs(&ctx).await?,
            );
            return Ok(shell::page(&ui, &nav(&ctx, &me).await?, title, body).into_response());
        }
    };
    let mut item = item.into_active_model();
    set(&mut item, params);
    item.update(&ctx.db).await?;
    Ok(ui.redirect(&action).ok("Saved.").into_response())
}

#[debug_handler]
async fn remove(
    auth: auth::JWT,
    ui: Ui,
    State(ctx): State<AppContext>,
    Path(id): Path<i64>,
) -> Result<Redirect> {
    let me = owner(&ctx, &auth).await?;
    load(&ctx, id, me.id)
        .await?
        .into_active_model()
        .delete(&ctx.db)
        .await?;
    Ok(ui.redirect("/tasks").ok("Deleted."))
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/tasks")
        .add("/", get(list).post(create))
        .add("/new", get(new))
        .add("/move", post(move_card))
        .add("/{id}", get(show).post(update))
        .add("/{id}/edit", get(edit))
        .add("/{id}/delete", post(remove))
}
