//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::note_tags::Entity as NoteTags;
pub use super::notebooks::Entity as Notebooks;
pub use super::notes::Entity as Notes;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
